// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtck9OJIVwuTor7es0Y6mUSWezF__O3cM',
    appId: '1:430808314566:web:6d5d86ec981db11aaeddc7',
    messagingSenderId: '430808314566',
    projectId: 'cetis-asistencia',
    authDomain: 'cetis-asistencia.firebaseapp.com',
    storageBucket: 'cetis-asistencia.firebasestorage.app',
    measurementId: 'G-ZPEZ401R42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh_XCY98esstDc80cEQqIRG6XstVbbX8g',
    appId: '1:430808314566:android:9ae083c60ac88c88aeddc7',
    messagingSenderId: '430808314566',
    projectId: 'cetis-asistencia',
    storageBucket: 'cetis-asistencia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKU9cLcvOJYWaIgNcCsff9m8n_x1vw_ng',
    appId: '1:430808314566:ios:4af801135fc980b1aeddc7',
    messagingSenderId: '430808314566',
    projectId: 'cetis-asistencia',
    storageBucket: 'cetis-asistencia.firebasestorage.app',
    iosBundleId: 'com.example.paseDeLista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKU9cLcvOJYWaIgNcCsff9m8n_x1vw_ng',
    appId: '1:430808314566:ios:4af801135fc980b1aeddc7',
    messagingSenderId: '430808314566',
    projectId: 'cetis-asistencia',
    storageBucket: 'cetis-asistencia.firebasestorage.app',
    iosBundleId: 'com.example.paseDeLista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtck9OJIVwuTor7es0Y6mUSWezF__O3cM',
    appId: '1:430808314566:web:c7128f30abf0b596aeddc7',
    messagingSenderId: '430808314566',
    projectId: 'cetis-asistencia',
    authDomain: 'cetis-asistencia.firebaseapp.com',
    storageBucket: 'cetis-asistencia.firebasestorage.app',
    measurementId: 'G-X8K24W7ZXC',
  );
}
